### ISSUE TITLE
Learning-SDN/Switch/OpenvSwitch/Walkthrough/頁面中的EXAMPLE 1指令錯嘍!

### ISSUE THREAD

**Issue by starcity1003** [OSE-Lab/Learning-SDN#47]
目前看到EXAMPLE 1的指令如下：
$ sudo ovs-appctl ofproto/trace br0 in_port=1,dl_dst=01:80:c2:00:00:10

但，跑到死也跑不出一樣的結果，因為dl_dst錯了！(跟EXAMPLE 2的一模一樣)
所以跑出的結果，與範例結果不可能相同！

範例裡的dl_dst是01:80:c2:00:00:05
所以指令應該是：
$ sudo ovs-appctl ofproto/trace br0 in_port=1,dl_dst=01:80:c2:00:00:05

**Comment by YanHaoChen** [comment]
感謝你的指正！
